### ISSUE TITLE
any example for createNote?

### ISSUE THREAD

**Issue by atian25** [yodasan/evernode#6]

**Comment by darobin** [comment]
I get the impression that createNote is broken. There is no way that I can see to call it without it blowing up:

TypeError: Object #<Object> has no method 'recv_'
    at exports.HTTPSConnection (/Projects/gladden/everest-js/evernode/lib/evernode/CustomConnections.js:57:37)
    at TBufferedTransport.receiver (/Projects/gladden/everest-js/node_modules/thrift/lib/thrift/transport.js:185:5)
    at EventEmitter.emit (events.js:88:17)
    at IncomingMessage.HTTPSConnection.responseCallBack.res.on.thisPtr.transmitting (/Projects/gladden/everest-js/evernode/lib/evernode/CustomConnections.js:114:17)
    at IncomingMessage.EventEmitter.emit (events.js:88:17)
    at IncomingMessage._emitData (http.js:359:10)
    at HTTPParser.parserOnBody [as onBody](http.js:123:21)
    at CleartextStream.socketOnData [as ondata](http.js:1356:20)
    at CleartextStream.CryptoStream._push (tls.js:396:27)
    at SecurePair.cycle (tls.js:750:20)
