### ISSUE TITLE
Crash with node (v0.8.19)

### ISSUE THREAD

**Issue by marcucio** [yodasan/evernode#7]
With the new version of node (v0.8.19) I am randomly getting the following error:

TypeError: Object # has no method 'recv_' at exports.HTTPSConnection (/var/www/html/plugins/cloudsnap-evernode/lib/evernode/CustomConnections.js:57:37) at TBufferedTransport.receiver (/var/www/html/plugins/wadey-node-thrift/lib/thrift/transport.js:185:5) at EventEmitter.emit (events.js:96:17) at IncomingMessage.HTTPSConnection.responseCallBack.res.on.thisPtr.transmitting (/var/www/html/plugins/cloudsnap-evernode/lib/evernode/CustomConnections.js:114:17) at IncomingMessage.EventEmitter.emit (events.js:96:17) at IncomingMessage._emitData (http.js:359:10) at HTTPParser.parserOnBody [as onBody](http.js:123:21) at CleartextStream.socketOnData [as ondata](http.js:1447:20) at CleartextStream.CryptoStream._push (tls.js:544:27) at SecurePair.cycle (tls.js:898:20)

I am looking into the issue now but I have been getting the crash at least once an hour in my app

**Comment by marcucio** [comment]
This version seems to have a fix in it for a simular bug:
https://github.com/berryboy/evernode/tree/master/lib/evernode
